name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Already using v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # Compatible with Node20

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Compatible with Node20
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Compatible with Node20

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Updated to v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/laravel:latest
